# Generated by Django 5.1.4 on 2025-01-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("COMPANIES", "0001_initial"),
        ("DEPARTMENTS", "0001_initial"),
        ("EMPLOYEES", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Project_comapny",
                        to="COMPANIES.company",
                    ),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_department",
                        to="DEPARTMENTS.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="EmployeeProject_Employee",
                        to="EMPLOYEES.employee",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="EmployeeProject_project",
                        to="PROJECTS.project",
                    ),
                ),
            ],
        ),
    ]
