# Generated by Django 5.1.4 on 2025-01-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("COMPANIES", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number_of_employees", models.IntegerField(default=0)),
                ("number_of_projects", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CompanyDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CompanyDepartment_Company",
                        to="COMPANIES.company",
                    ),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CompanyDepartment_department",
                        to="DEPARTMENTS.department",
                    ),
                ),
            ],
        ),
    ]
