# Generated by Django 5.1.4 on 2025-01-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMPLOYEES", "0001_initial"),
        ("USER_ACCOUNTS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="employee_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="EMPLOYEES.employee",
            ),
            preserve_default=False,
        ),
    ]
