# Generated by Django 5.1.4 on 2025-01-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMPLOYEES", "0001_initial"),
        ("USER_ACCOUNTS", "0002_alter_useraccount_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="employee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_account",
                to="EMPLOYEES.employee",
            ),
        ),
    ]
