# Generated by Django 5.1.4 on 2025-01-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("COMPANIES", "0001_initial"),
        ("DEPARTMENTS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("designation", models.CharField(max_length=100)),
                ("hired_on", models.DateField(blank=True, null=True)),
                ("days_employed", models.IntegerField(default=0)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_employee",
                        to="COMPANIES.company",
                    ),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_employee",
                        to="DEPARTMENTS.department",
                    ),
                ),
            ],
        ),
    ]
