# Generated by Django 5.1.4 on 2025-01-13 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCycle",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Pending Review", "Pending Review"),
                            ("Review Scheduled", "Review Scheduled"),
                            ("Feedback Provided", "Feedback Provided"),
                            ("Under Approval", "Under Approval"),
                            ("Review Approved", "Review Approved"),
                            ("Review Rejected", "Review Rejected"),
                        ],
                        default="Pending Review",
                        max_length=50,
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_cycles_employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        limit_choices_to={"role": "manager"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_cycles_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "stage"), name="unique_employee_stage"
                    )
                ],
            },
        ),
    ]
