# Generated by Django 5.1.4 on 2025-01-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMPLOYEES", "0001_initial"),
        ("ReviewCycle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewcycle",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_cycles_employee",
                to="EMPLOYEES.employee",
            ),
        ),
        migrations.AlterField(
            model_name="reviewcycle",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reviewcycle",
            name="manager",
            field=models.ForeignKey(
                limit_choices_to={"role": "manager"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_cycles_manager",
                to="EMPLOYEES.employee",
            ),
        ),
    ]
