# Generated by Django 5.1.4 on 2025-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReviewCycle", "0003_stage_alter_reviewcycle_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="next_stage",
            field=models.ManyToManyField(
                blank=True, related_name="previous_stage", to="ReviewCycle.stage"
            ),
        ),
    ]
