# Generated by Django 5.1.4 on 2025-01-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReviewCycle", "0004_stage_next_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="next_stage",
        ),
        migrations.AddField(
            model_name="stage",
            name="next_stage",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_stage",
                to="ReviewCycle.stage",
            ),
            preserve_default=False,
        ),
    ]
