# Generated by Django 5.1.4 on 2025-01-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number_of_departments", models.IntegerField(default=0)),
                ("number_of_employees", models.IntegerField(default=0)),
                ("number_of_projects", models.IntegerField(default=0)),
            ],
        ),
    ]
